name: Test

on:

  workflow_dispatch:

jobs:

  test:
    runs-on: ubuntu-20.04

    steps:
      - name: Check Out
        uses: actions/checkout@v2
      
      - name: Random
        id: continueToRun
        run: python ./src/rand.py
        continue-on-error: true

      - name: Datetime
        if:  ${{ contains(steps.continueToRun.outcome, 'success') }}
        run: date
      
      - name: Install Selenium
        if:  ${{ contains(steps.continueToRun.outcome, 'success') }}
        run: pip install selenium