name: Test

on:

  workflow_dispatch:

jobs:

  test:
    runs-on: ubuntu-20.04

    steps:
      - name: Check Out
        uses: actions/checkout@v2
        
      - name: Datetime
        run: date
      
      - name: Install Selenium
        run: pip install selenium

      - name: Test
        env: 
          MY_SECRET_USERNAME: ${{ secrets.MY_SECRET_USERNAME }}
          MY_SECRET_PASSWORD: ${{ secrets.MY_SECRET_PASSWORD }}
          MY_SECRET_LOCATION: ${{ secrets.MY_SECRET_LOCATION }}
        run: python ./src/test.py